name: qrscan_example
description: Demonstrates how to use the qrscan plugin.
publish_to: "none"
version: 0.4.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  qrscan:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/generate_qrcode.png
    - images/scanner.png
    - images/albums.png
